### ISSUE TITLE
V1 - Update front-end dashboard 

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-node-manager-plugin#25]
**Context**
The node-manager V1 details are here: https://www.notion.so/massa-innoteam/Node-Manager-Staking-5870cb48b50741cea3ba83d2c6ac4fb4?pvs=4#49a7bdeb12914a049d0fa410215a254b 

The objective of this ticket is to update the front-end to display new and meaningful information that have been added to the back end.

**How to**

- [ ] Use existing framework 
- [ ] Surafe node & Staking info in the front

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
*Does this task require some QA tests ?*
*If yes, explain how to validate it*

**Comment by 0xMazout** [comment]
ATM Solving problems to test the node manager in local

**Comment by 0xMazout** [comment]
To test this in local mode, uncomment the line 28 of the request.ts file. comment the line 26

Launch the backend , copy the :port gived by the backend then paste it in the line 28
